/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\clown.glb --types --transform 
Files: .\clown.glb [6.68MB] > C:\Users\Nathan Adhitya\Documents\clown-transformed.glb [789.56KB] (88%)
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        WhiteClown: THREE.SkinnedMesh;
        mixamorigHips: THREE.Bone;
    };
    materials: {
        WhiteClown_material: THREE.MeshStandardMaterial;
    };
    animations: GLTFAction[];
};

type ActionName = "Idle" | "Pulling" | "Running" | "Walking";
interface GLTFAction extends THREE.AnimationClip {
    name: ActionName;
}
type ContextType = Record<
    string,
    React.ForwardRefExoticComponent<
        JSX.IntrinsicElements["skinnedMesh"] | JSX.IntrinsicElements["bone"]
    >
>;

export function Clown(props: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
    const { nodes, materials, animations } = useGLTF(
        "/clown-transformed.glb"
    ) as GLTFResult;
    const { actions } = useAnimations<GLTFAction>(animations, group);

    useEffect(() => {
        actions.Idle?.play();
    }, [actions]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                    name="Armature"
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                >
                    <primitive object={nodes.mixamorigHips} />
                </group>
                <skinnedMesh
                    name="WhiteClown"
                    geometry={nodes.WhiteClown.geometry}
                    material={materials.WhiteClown_material}
                    skeleton={nodes.WhiteClown.skeleton}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={0.01}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/clown-transformed.glb");
